window.MWAP_CURATED_GALLERIES = {
  "meher-aman": [
    "/assets/portfolio/curated/meher-aman/engagement1.jpg",
    "/assets/portfolio/curated/meher-aman/mehendihaldi1.jpg",
    "/assets/portfolio/curated/meher-aman/sangeet1.jpg",
    "/assets/portfolio/curated/meher-aman/sufi1.jpg",
    "/assets/portfolio/curated/meher-aman/wedding1.jpg",
    "/assets/portfolio/curated/meher-aman/engagement2.jpg",
    "/assets/portfolio/curated/meher-aman/mehendihaldi2.jpg",
    "/assets/portfolio/curated/meher-aman/sangeet2.jpg",
    "/assets/portfolio/curated/meher-aman/sufi2.jpg",
    "/assets/portfolio/curated/meher-aman/wedding2.jpg",
    "/assets/portfolio/curated/meher-aman/engagement3.jpg",
    "/assets/portfolio/curated/meher-aman/mehendihaldi3.jpg",
    "/assets/portfolio/curated/meher-aman/sangeet3.jpg",
    "/assets/portfolio/curated/meher-aman/sufi3.jpg",
    "/assets/portfolio/curated/meher-aman/wedding3.jpg",
    "/assets/portfolio/curated/meher-aman/engagement4.jpg",
    "/assets/portfolio/curated/meher-aman/mehendihaldi4.jpg",
    "/assets/portfolio/curated/meher-aman/sangeet4.jpg",
    "/assets/portfolio/curated/meher-aman/sufi4.jpg",
    "/assets/portfolio/curated/meher-aman/wedding4.jpg",
    "/assets/portfolio/curated/meher-aman/engagement5.jpg",
    "/assets/portfolio/curated/meher-aman/mehendihaldi5.jpg",
    "/assets/portfolio/curated/meher-aman/sangeet5.jpg",
    "/assets/portfolio/curated/meher-aman/sufi5.jpg"
  ],
  "bindya-shiven": [
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi1.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception1.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding1.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi2.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception2.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding2.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi3.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception3.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding3.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi4.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception4.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding4.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi5.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception5.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding5.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi6.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception6.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding6.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi7.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception7.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding7.jpg",
    "/assets/portfolio/curated/bindya-shiven/cocktailhaldi8.jpg",
    "/assets/portfolio/curated/bindya-shiven/reception8.jpg",
    "/assets/portfolio/curated/bindya-shiven/wedding8.jpg"
  ],
  "juhi-jatin": [
    "/assets/portfolio/curated/juhi-jatin/haldi1.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi1.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception1.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet1.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding1.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi2.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi2.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception2.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet2.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding2.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi3.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi3.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception3.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet3.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding3.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi4.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi4.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception4.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet4.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding4.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi5.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi5.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception5.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet5.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding5.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi6.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi6.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception6.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet6.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding6.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi7.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi7.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception7.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet7.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding7.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi8.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi8.jpg",
    "/assets/portfolio/curated/juhi-jatin/reception8.jpg",
    "/assets/portfolio/curated/juhi-jatin/sangeet8.jpg",
    "/assets/portfolio/curated/juhi-jatin/wedding8.jpg",
    "/assets/portfolio/curated/juhi-jatin/haldi9.jpg",
    "/assets/portfolio/curated/juhi-jatin/mehendi9.jpg"
  ],
  "manat-samrath": [
    "/assets/portfolio/curated/manat-samrath/anandkaraj1.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi1.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi1.jpg",
    "/assets/portfolio/curated/manat-samrath/reception1.jpg",
    "/assets/portfolio/curated/manat-samrath/anandkaraj2.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi2.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi2.jpg",
    "/assets/portfolio/curated/manat-samrath/reception2.jpg",
    "/assets/portfolio/curated/manat-samrath/anandkaraj3.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi3.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi3.jpg",
    "/assets/portfolio/curated/manat-samrath/reception3.jpg",
    "/assets/portfolio/curated/manat-samrath/anandkaraj4.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi4.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi4.jpg",
    "/assets/portfolio/curated/manat-samrath/reception4.jpg",
    "/assets/portfolio/curated/manat-samrath/anandkaraj5.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi5.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi5.jpg",
    "/assets/portfolio/curated/manat-samrath/reception5.jpg",
    "/assets/portfolio/curated/manat-samrath/anandkaraj6.jpg",
    "/assets/portfolio/curated/manat-samrath/cocktailsufi6.jpg",
    "/assets/portfolio/curated/manat-samrath/haldi6.jpg",
    "/assets/portfolio/curated/manat-samrath/reception6.jpg"
  ],
  "mithali-arjun": [
    "/assets/portfolio/curated/mithali-arjun/cocktail1.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol1.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi1.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding1.jpg",
    "/assets/portfolio/curated/mithali-arjun/cocktail2.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol2.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi2.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding2.jpg",
    "/assets/portfolio/curated/mithali-arjun/cocktail3.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol3.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi3.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding3.jpg",
    "/assets/portfolio/curated/mithali-arjun/cocktail4.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol4.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi4.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding4.jpg",
    "/assets/portfolio/curated/mithali-arjun/cocktail5.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol5.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi5.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding5.jpg",
    "/assets/portfolio/curated/mithali-arjun/cocktail6.jpg",
    "/assets/portfolio/curated/mithali-arjun/dhol6.jpg",
    "/assets/portfolio/curated/mithali-arjun/mehendi6.jpg",
    "/assets/portfolio/curated/mithali-arjun/wedding6.jpg"
  ],
  "ria-pranav": [
    "/assets/portfolio/curated/ria-pranav/cocktail1.jpg",
    "/assets/portfolio/curated/ria-pranav/dhol1.jpg",
    "/assets/portfolio/curated/ria-pranav/satsang1.jpg",
    "/assets/portfolio/curated/ria-pranav/haldi1.jpg",
    "/assets/portfolio/curated/ria-pranav/mehendi1.jpg",
    "/assets/portfolio/curated/ria-pranav/mehendi3.jpg",
    "/assets/portfolio/curated/ria-pranav/sainth1.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding1.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding3.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding5.jpg",
    "/assets/portfolio/curated/ria-pranav/cocktail2.jpg",
    "/assets/portfolio/curated/ria-pranav/dhol2.jpg",
    "/assets/portfolio/curated/ria-pranav/satsang2.jpg",
    "/assets/portfolio/curated/ria-pranav/haldi2.jpg",
    "/assets/portfolio/curated/ria-pranav/mehendi2.jpg",
    "/assets/portfolio/curated/ria-pranav/mehendi4.jpg",
    "/assets/portfolio/curated/ria-pranav/sainth2.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding2.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding4.jpg",
    "/assets/portfolio/curated/ria-pranav/wedding6.jpg",
    "/assets/portfolio/curated/ria-pranav/cocktail3.jpg",
    "/assets/portfolio/curated/ria-pranav/dhol3.jpg",
    "/assets/portfolio/curated/ria-pranav/satsang3.jpg",
    "/assets/portfolio/curated/ria-pranav/haldi3.jpg"
  ],
  "jigyasa-samar": [
    "/assets/portfolio/curated/jigyasa-samar/mehendi1.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi1.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding1.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner1.jpg",
    "/assets/portfolio/curated/jigyasa-samar/mehendi2.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi2.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding2.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner2.jpg",
    "/assets/portfolio/curated/jigyasa-samar/mehendi3.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi3.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding3.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner3.jpg",
    "/assets/portfolio/curated/jigyasa-samar/mehendi4.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi4.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding4.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner4.jpg",
    "/assets/portfolio/curated/jigyasa-samar/mehendi5.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi5.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding5.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner5.jpg",
    "/assets/portfolio/curated/jigyasa-samar/mehendi6.jpg",
    "/assets/portfolio/curated/jigyasa-samar/sangeethaldi6.jpg",
    "/assets/portfolio/curated/jigyasa-samar/wedding6.jpg",
    "/assets/portfolio/curated/jigyasa-samar/welcomedinner6.jpg"
  ],
  "sana-sahas": [
    "/assets/portfolio/curated/sana-sahas/engagement1.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi1.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding1.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement2.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi2.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding2.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement3.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi3.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding3.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement4.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi4.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding4.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement5.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi5.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding5.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement6.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi6.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding6.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement7.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi7.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding7.jpg",
    "/assets/portfolio/curated/sana-sahas/engagement8.jpg",
    "/assets/portfolio/curated/sana-sahas/mehendi8.jpg",
    "/assets/portfolio/curated/sana-sahas/wedding8.jpg"
  ],
  "sehaj-harsimar": [
    "/assets/portfolio/curated/sehaj-harsimar/haldichooda1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/mehendi1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sagankirtan1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/wedding1.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/haldichooda2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/mehendi2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sagankirtan2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/wedding2.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/haldichooda3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/mehendi3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sagankirtan3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/wedding3.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/haldichooda4.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/mehendi4.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty4.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sagankirtan4.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement4.jpg",
    "/assets/portfolio/curated/sehaj-harsimar/wedding4.jpg"
  ],
  "sudeep-ashween": [
    "/assets/portfolio/curated/sudeep-ashween/mehendi1.jpg",
    "/assets/portfolio/curated/sudeep-ashween/haldi1.jpg",
    "/assets/portfolio/curated/sudeep-ashween/hinduwedding1.jpg",
    "/assets/portfolio/curated/sudeep-ashween/roka1.jpg",
    "/assets/portfolio/curated/sudeep-ashween/sikhwedding1.jpg",
    "/assets/portfolio/curated/sudeep-ashween/mehendi2.jpg",
    "/assets/portfolio/curated/sudeep-ashween/haldi2.jpg",
    "/assets/portfolio/curated/sudeep-ashween/hinduwedding2.jpg",
    "/assets/portfolio/curated/sudeep-ashween/roka2.jpg",
    "/assets/portfolio/curated/sudeep-ashween/sikhwedding2.jpg",
    "/assets/portfolio/curated/sudeep-ashween/mehendi3.jpg",
    "/assets/portfolio/curated/sudeep-ashween/haldi3.jpg",
    "/assets/portfolio/curated/sudeep-ashween/hinduwedding3.jpg",
    "/assets/portfolio/curated/sudeep-ashween/roka3.jpg",
    "/assets/portfolio/curated/sudeep-ashween/sikhwedding3.jpg",
    "/assets/portfolio/curated/sudeep-ashween/mehendi4.jpg",
    "/assets/portfolio/curated/sudeep-ashween/haldi4.jpg",
    "/assets/portfolio/curated/sudeep-ashween/hinduwedding4.jpg",
    "/assets/portfolio/curated/sudeep-ashween/roka4.jpg",
    "/assets/portfolio/curated/sudeep-ashween/sikhwedding4.jpg",
    "/assets/portfolio/curated/sudeep-ashween/mehendi5.jpg",
    "/assets/portfolio/curated/sudeep-ashween/haldi5.jpg",
    "/assets/portfolio/curated/sudeep-ashween/hinduwedding5.jpg",
    "/assets/portfolio/curated/sudeep-ashween/roka5.jpg"
  ],
  "tanvi-uday": [
    "/assets/portfolio/curated/tanvi-uday/mehendi1.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda1.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet1.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding1.jpg",
    "/assets/portfolio/curated/tanvi-uday/mehendi2.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda2.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet2.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding2.jpg",
    "/assets/portfolio/curated/tanvi-uday/mehendi3.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda3.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet3.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding3.jpg",
    "/assets/portfolio/curated/tanvi-uday/mehendi4.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda4.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet4.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding4.jpg",
    "/assets/portfolio/curated/tanvi-uday/mehendi5.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda5.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet5.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding5.jpg",
    "/assets/portfolio/curated/tanvi-uday/mehendi6.jpg",
    "/assets/portfolio/curated/tanvi-uday/pathchooda6.jpg",
    "/assets/portfolio/curated/tanvi-uday/sangeet6.jpg",
    "/assets/portfolio/curated/tanvi-uday/wedding6.jpg"
  ]
};

window.MWAP_CURATED_RATIOS = {
  "/assets/portfolio/curated/meher-aman/engagement1.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/mehendihaldi1.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/sangeet1.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sufi1.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/wedding1.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/engagement2.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/mehendihaldi2.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sangeet2.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sufi2.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/wedding2.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/engagement3.jpg": 0.664,
  "/assets/portfolio/curated/meher-aman/mehendihaldi3.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/sangeet3.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sufi3.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/wedding3.jpg": 0.685,
  "/assets/portfolio/curated/meher-aman/engagement4.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/mehendihaldi4.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sangeet4.jpg": 0.667,
  "/assets/portfolio/curated/meher-aman/sufi4.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/wedding4.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/engagement5.jpg": 0.713,
  "/assets/portfolio/curated/meher-aman/mehendihaldi5.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sangeet5.jpg": 1.5,
  "/assets/portfolio/curated/meher-aman/sufi5.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi1.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/reception1.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding1.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi2.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/reception2.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding2.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi3.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/reception3.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding3.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi4.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/reception4.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding4.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi5.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/reception5.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/wedding5.jpg": 0.8,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi6.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/reception6.jpg": 1.4,
  "/assets/portfolio/curated/bindya-shiven/wedding6.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi7.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/reception7.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding7.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/cocktailhaldi8.jpg": 0.667,
  "/assets/portfolio/curated/bindya-shiven/reception8.jpg": 1.5,
  "/assets/portfolio/curated/bindya-shiven/wedding8.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi1.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/mehendi1.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/reception1.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/sangeet1.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/wedding1.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi2.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/mehendi2.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/reception2.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/sangeet2.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/wedding2.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi3.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/mehendi3.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/reception3.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/sangeet3.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/wedding3.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi4.jpg": 0.651,
  "/assets/portfolio/curated/juhi-jatin/mehendi4.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/reception4.jpg": 1.401,
  "/assets/portfolio/curated/juhi-jatin/sangeet4.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/wedding4.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/haldi5.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/mehendi5.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/reception5.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/sangeet5.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/wedding5.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi6.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/mehendi6.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/reception6.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/sangeet6.jpg": 1.499,
  "/assets/portfolio/curated/juhi-jatin/wedding6.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/haldi7.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/mehendi7.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/reception7.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/sangeet7.jpg": 1.401,
  "/assets/portfolio/curated/juhi-jatin/wedding7.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi8.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/mehendi8.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/reception8.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/sangeet8.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/wedding8.jpg": 0.667,
  "/assets/portfolio/curated/juhi-jatin/haldi9.jpg": 1.5,
  "/assets/portfolio/curated/juhi-jatin/mehendi9.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/anandkaraj1.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi1.jpg": 0.8,
  "/assets/portfolio/curated/manat-samrath/haldi1.jpg": 0.667,
  "/assets/portfolio/curated/manat-samrath/reception1.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/anandkaraj2.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi2.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/haldi2.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/reception2.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/anandkaraj3.jpg": 1,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi3.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/haldi3.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/reception3.jpg": 0.667,
  "/assets/portfolio/curated/manat-samrath/anandkaraj4.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi4.jpg": 0.667,
  "/assets/portfolio/curated/manat-samrath/haldi4.jpg": 1.25,
  "/assets/portfolio/curated/manat-samrath/reception4.jpg": 0.624,
  "/assets/portfolio/curated/manat-samrath/anandkaraj5.jpg": 0.667,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi5.jpg": 0.667,
  "/assets/portfolio/curated/manat-samrath/haldi5.jpg": 1.25,
  "/assets/portfolio/curated/manat-samrath/reception5.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/anandkaraj6.jpg": 1.5,
  "/assets/portfolio/curated/manat-samrath/cocktailsufi6.jpg": 1.25,
  "/assets/portfolio/curated/manat-samrath/haldi6.jpg": 1.401,
  "/assets/portfolio/curated/manat-samrath/reception6.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/cocktail1.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/dhol1.jpg": 1.49,
  "/assets/portfolio/curated/mithali-arjun/mehendi1.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/wedding1.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/cocktail2.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/dhol2.jpg": 1.399,
  "/assets/portfolio/curated/mithali-arjun/mehendi2.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/wedding2.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/cocktail3.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/dhol3.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/mehendi3.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/wedding3.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/cocktail4.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/dhol4.jpg": 0.681,
  "/assets/portfolio/curated/mithali-arjun/mehendi4.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/wedding4.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/cocktail5.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/dhol5.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/mehendi5.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/wedding5.jpg": 0.667,
  "/assets/portfolio/curated/mithali-arjun/cocktail6.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/dhol6.jpg": 0.697,
  "/assets/portfolio/curated/mithali-arjun/mehendi6.jpg": 1.5,
  "/assets/portfolio/curated/mithali-arjun/wedding6.jpg": 0.667,
  "/assets/portfolio/curated/ria-pranav/cocktail1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/dhol1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/satsang1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/haldi1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/mehendi1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/mehendi3.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/sainth1.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/wedding1.jpg": 0.667,
  "/assets/portfolio/curated/ria-pranav/wedding3.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/wedding5.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/cocktail2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/dhol2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/satsang2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/haldi2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/mehendi2.jpg": 0.667,
  "/assets/portfolio/curated/ria-pranav/mehendi4.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/sainth2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/wedding2.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/wedding4.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/wedding6.jpg": 0.667,
  "/assets/portfolio/curated/ria-pranav/cocktail3.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/dhol3.jpg": 1.5,
  "/assets/portfolio/curated/ria-pranav/satsang3.jpg": 0.667,
  "/assets/portfolio/curated/ria-pranav/haldi3.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/mehendi1.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi1.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/wedding1.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner1.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/mehendi2.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi2.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/wedding2.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner2.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/mehendi3.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi3.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/wedding3.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner3.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/mehendi4.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi4.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/wedding4.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner4.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/mehendi5.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi5.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/wedding5.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner5.jpg": 1.5,
  "/assets/portfolio/curated/jigyasa-samar/mehendi6.jpg": 0.667,
  "/assets/portfolio/curated/jigyasa-samar/sangeethaldi6.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/wedding6.jpg": 1.501,
  "/assets/portfolio/curated/jigyasa-samar/welcomedinner6.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/engagement1.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/mehendi1.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/wedding1.jpg": 1.5,
  "/assets/portfolio/curated/sana-sahas/engagement2.jpg": 1.501,
  "/assets/portfolio/curated/sana-sahas/mehendi2.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/wedding2.jpg": 1.5,
  "/assets/portfolio/curated/sana-sahas/engagement3.jpg": 1.5,
  "/assets/portfolio/curated/sana-sahas/mehendi3.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/wedding3.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/engagement4.jpg": 1.501,
  "/assets/portfolio/curated/sana-sahas/mehendi4.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/wedding4.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/engagement5.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/mehendi5.jpg": 1.501,
  "/assets/portfolio/curated/sana-sahas/wedding5.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/engagement6.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/mehendi6.jpg": 1.501,
  "/assets/portfolio/curated/sana-sahas/wedding6.jpg": 1.5,
  "/assets/portfolio/curated/sana-sahas/engagement7.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/mehendi7.jpg": 0.666,
  "/assets/portfolio/curated/sana-sahas/wedding7.jpg": 0.667,
  "/assets/portfolio/curated/sana-sahas/engagement8.jpg": 1.5,
  "/assets/portfolio/curated/sana-sahas/mehendi8.jpg": 1.501,
  "/assets/portfolio/curated/sana-sahas/wedding8.jpg": 1.5,
  "/assets/portfolio/curated/sehaj-harsimar/haldichooda1.jpg": 1.78,
  "/assets/portfolio/curated/sehaj-harsimar/mehendi1.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty1.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/sagankirtan1.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement1.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/wedding1.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/haldichooda2.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/mehendi2.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty2.jpg": 1.5,
  "/assets/portfolio/curated/sehaj-harsimar/sagankirtan2.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement2.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/wedding2.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/haldichooda3.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/mehendi3.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty3.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/sagankirtan3.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement3.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/wedding3.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/haldichooda4.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/mehendi4.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/receptionafterparty4.jpg": 1.5,
  "/assets/portfolio/curated/sehaj-harsimar/sagankirtan4.jpg": 0.666,
  "/assets/portfolio/curated/sehaj-harsimar/sangeetengagement4.jpg": 1.501,
  "/assets/portfolio/curated/sehaj-harsimar/wedding4.jpg": 1.501,
  "/assets/portfolio/curated/sudeep-ashween/mehendi1.jpg": 0.667,
  "/assets/portfolio/curated/sudeep-ashween/haldi1.jpg": 1.503,
  "/assets/portfolio/curated/sudeep-ashween/hinduwedding1.jpg": 0.667,
  "/assets/portfolio/curated/sudeep-ashween/roka1.jpg": 0.667,
  "/assets/portfolio/curated/sudeep-ashween/sikhwedding1.jpg": 0.667,
  "/assets/portfolio/curated/sudeep-ashween/mehendi2.jpg": 1.5,
  "/assets/portfolio/curated/sudeep-ashween/haldi2.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/hinduwedding2.jpg": 0.667,
  "/assets/portfolio/curated/sudeep-ashween/roka2.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/sikhwedding2.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/mehendi3.jpg": 1.5,
  "/assets/portfolio/curated/sudeep-ashween/haldi3.jpg": 1.503,
  "/assets/portfolio/curated/sudeep-ashween/hinduwedding3.jpg": 0.666,
  "/assets/portfolio/curated/sudeep-ashween/roka3.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/sikhwedding3.jpg": 0.665,
  "/assets/portfolio/curated/sudeep-ashween/mehendi4.jpg": 1.78,
  "/assets/portfolio/curated/sudeep-ashween/haldi4.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/hinduwedding4.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/roka4.jpg": 1.5,
  "/assets/portfolio/curated/sudeep-ashween/sikhwedding4.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/mehendi5.jpg": 1.78,
  "/assets/portfolio/curated/sudeep-ashween/haldi5.jpg": 1.504,
  "/assets/portfolio/curated/sudeep-ashween/hinduwedding5.jpg": 0.665,
  "/assets/portfolio/curated/sudeep-ashween/roka5.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/mehendi1.jpg": 0.649,
  "/assets/portfolio/curated/tanvi-uday/pathchooda1.jpg": 0.723,
  "/assets/portfolio/curated/tanvi-uday/sangeet1.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/wedding1.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/mehendi2.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/pathchooda2.jpg": 0.688,
  "/assets/portfolio/curated/tanvi-uday/sangeet2.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/wedding2.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/mehendi3.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/pathchooda3.jpg": 1.434,
  "/assets/portfolio/curated/tanvi-uday/sangeet3.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/wedding3.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/mehendi4.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/pathchooda4.jpg": 0.678,
  "/assets/portfolio/curated/tanvi-uday/sangeet4.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/wedding4.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/mehendi5.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/pathchooda5.jpg": 1.457,
  "/assets/portfolio/curated/tanvi-uday/sangeet5.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/wedding5.jpg": 1.429,
  "/assets/portfolio/curated/tanvi-uday/mehendi6.jpg": 1.5,
  "/assets/portfolio/curated/tanvi-uday/pathchooda6.jpg": 0.676,
  "/assets/portfolio/curated/tanvi-uday/sangeet6.jpg": 0.667,
  "/assets/portfolio/curated/tanvi-uday/wedding6.jpg": 1.456
};


window.MWAP_PORTFOLIO = [
  {
    slug: "delhi",
    name: "Delhi",
    cover: "/assets/portfolio/delhi/bindya-shiven/01.jpg",
    intro: "Grand rooms, intimate gestures and celebrations shaped with unmistakable Delhi energy.",
    events: [
      {
        slug: "mithali-arjun",
        title: "Mithali & Arjun",
        label: "Wedding · Delhi",
        cover: "/assets/portfolio/delhi/mithali-arjun/wedding-portrait.jpg",
        writeup: "",
        author: "",
        images: [
          "/assets/portfolio/delhi/mithali-arjun/wedding-portrait.jpg",
          ...window.MWAP_CURATED_GALLERIES["mithali-arjun"]
        ]
      },
      {
        slug: "bindya-shiven",
        title: "Bindya & Shiven",
        label: "Wedding · Delhi",
        cover: "/assets/portfolio/delhi/bindya-shiven/01.jpg",
        writeup: "Our experience with MWP was nothing short of spectacular.\n\nJD and his team completely flipped the script on wedding stress. They were always a step ahead with multiple options and seamless backup plans—even handling unexpected wedding-day rain so beautifully that our guests didn't feel a thing.\n\nMost importantly, they shielded our family from all the chaos, allowing us to fully immerse ourselves in the joy of the day. If you want a relaxed journey and a wedding you can actually enjoy, we whole-heartedly recommend MWP!",
        author: "Bindya & Shiven",
        images: window.MWAP_CURATED_GALLERIES["bindya-shiven"]
      },
      {
        slug: "tanvi-uday",
        title: "Tanvi & Uday",
        label: "Wedding · Delhi",
        cover: "/assets/portfolio/delhi/tanvi-uday/featured.jpg",
        writeup: "",
        author: "",
        images: window.MWAP_CURATED_GALLERIES["tanvi-uday"]
      }
    ]
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    cover: "/assets/portfolio/jaipur/meher-aman/featured.jpg",
    intro: "Palace silhouettes, warm stone and celebrations that carry the romance of Rajasthan.",
    events: [
      {
        slug: "meher-aman",
        title: "Meher & Aman",
        label: "Wedding · Jaipur",
        cover: "/assets/portfolio/jaipur/meher-aman/featured.jpg",
        writeup: "",
        author: "",
        images: [
          "/assets/portfolio/jaipur/meher-aman/featured.jpg",
          ...window.MWAP_CURATED_GALLERIES["meher-aman"]
        ]
      },
      {
        slug: "manat-samrath",
        title: "Manat & Samrath",
        label: "Wedding · Jaipur",
        cover: "/assets/portfolio/jaipur/manat-samrath/01.jpg",
        writeup: "",
        author: "",
        images: window.MWAP_CURATED_GALLERIES["manat-samrath"]
      }
    ]
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    cover: "/assets/portfolio/udaipur/jigyasa-samar/01.jpg",
    intro: "Lakeside light, royal settings and stories designed to unfold with quiet grandeur.",
    events: [
      {
        slug: "sehaj-harsimar",
        title: "Sehaj & Harsimar",
        label: "Wedding · Udaipur",
        cover: "/assets/portfolio/udaipur/sehaj-harsimar/featured.jpg",
        writeup: "I needed was best wedding planner whom I could trust with everything, and I had the best person as Jaideep who is not just a friend but also like my family now.\n\nDue to his creative vision each and everything was catered with lots of love and care.\n\nIt was not wedding but a festival of celebrations and that wouldn’t have been possible without Jaideep and his MWP Army",
        author: "Sehaj & Harsimar",
        images: window.MWAP_CURATED_GALLERIES["sehaj-harsimar"]
      },
      {
        slug: "jigyasa-samar",
        title: "Jigyasa & Samar",
        label: "Wedding · Udaipur",
        cover: "/assets/portfolio/udaipur/jigyasa-samar/01.jpg",
        writeup: "Everything was simply perfect.\n\nWe connected with JD through Instagram, and we never imagined it would turn into such an incredible experience.\n\nJD has a charm, and together with his amazing team, he created absolute magic.\n\nThe hospitality was appreciated by every single guest, and both our families were beyond happy with how everything was managed.\n\nThe three days flew by so quickly—we truly wish we could relive every moment. Thank you for making our celebration so unforgettable!",
        author: "Jigyasa & Samar",
        images: window.MWAP_CURATED_GALLERIES["jigyasa-samar"]
      }
    ]
  },
  {
    slug: "goa",
    name: "Goa",
    cover: "/assets/portfolio/goa/juhi-jatin/featured.jpg",
    intro: "Sunlit revelry, tropical colour and celebrations made to feel beautifully unbuttoned.",
    events: [{
      slug: "juhi-jatin",
      title: "Juhi & Jatin",
      label: "Wedding · Goa",
      cover: "/assets/portfolio/goa/juhi-jatin/featured.jpg",
      writeup: "",
      author: "",
      images: window.MWAP_CURATED_GALLERIES["goa/juhi-jatin"]
    }]
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    cover: "/assets/destinations/Mumbai/0Z0A8551.JPG",
    intro: "High-energy evenings and immersive worlds in the city that never stops moving.",
    events: [{
      slug: "icwf-25",
      title: "ICWF",
      label: "Experience · Mumbai",
      cover: "/assets/destinations/Mumbai/0Z0A8551.JPG",
      writeup: "",
      author: "",
      images: [
        "/assets/destinations/Mumbai/0Z0A8551.JPG",
        "/assets/destinations/Mumbai/0Z0A8175.JPG",
        "/assets/destinations/Mumbai/SPMO9881.JPG",
        "/assets/destinations/Mumbai/0Z0A8549.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A6256.JPG",
        "/assets/portfolio/mumbai/icwf-25/SPMO4982.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A6331.JPG",
        "/assets/portfolio/mumbai/icwf-25/SPMO4371.JPG",
        "/assets/portfolio/mumbai/icwf-25/_E1A3416.JPG",
        "/assets/portfolio/mumbai/icwf-25/_E1A4027.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A0119.JPG?v=2",
        "/assets/portfolio/mumbai/icwf-25/0Z0A6225.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A7050.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A7734.JPG",
        "/assets/portfolio/mumbai/icwf-25/0Z0A9027.JPG"
      ]
    }]
  },
  {
    slug: "bangalore",
    name: "Bangalore",
    cover: "/assets/destinations/bangalore/1.jpg",
    intro: "Garden-city ease met with expressive detail, colour and contemporary celebration.",
    events: [{
      slug: "icwf",
      title: "ICWF",
      label: "Experience · Bangalore",
      cover: "/assets/destinations/bangalore/1.jpg",
      writeup: "",
      author: "",
      images: [
        "/assets/destinations/bangalore/1.jpg",
        "/assets/destinations/bangalore/2.jpg",
        "/assets/destinations/bangalore/3.png",
        "/assets/destinations/bangalore/4.png",
        "/assets/destinations/bangalore/5.png",
        "/assets/portfolio/bangalore/icwf-2022/1.jpg",
        "/assets/portfolio/bangalore/icwf-2022/2.jpg",
        "/assets/portfolio/bangalore/icwf-2022/3.jpg",
        "/assets/portfolio/bangalore/icwf-2022/4.jpg",
        "/assets/portfolio/bangalore/icwf-2022/5.jpg",
        "/assets/portfolio/bangalore/icwf-2022/6.jpg",
        "/assets/portfolio/bangalore/icwf-2022/7.jpg",
        "/assets/portfolio/bangalore/icwf-2022/8.jpg",
        "/assets/portfolio/bangalore/icwf-2022/9.jpg",
        "/assets/portfolio/bangalore/icwf-2022/10.jpg"
      ]
    }]
  },
  {
    slug: "indore",
    name: "Indore",
    cover: "/assets/portfolio/indore/juhi-jatin/featured.jpg",
    intro: "A vivid celebration of ritual, family and the colour of coming together.",
    events: [{
      slug: "juhi-jatin",
      title: "Juhi & Jatin",
      label: "Wedding · Indore",
      cover: "/assets/portfolio/indore/juhi-jatin/featured.jpg",
      writeup: "",
      author: "",
      images: window.MWAP_CURATED_GALLERIES["juhi-jatin"].filter((_, index) => index % 2 === 1)
    }]
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    cover: "/assets/destinations/Kolkata/1.jpg",
    intro: "Artistry, heritage and intimate storytelling in a city with a singular soul.",
    events: [{
      slug: "icwf",
      title: "ICWF",
      label: "Experience · Kolkata",
      cover: "/assets/destinations/Kolkata/1.jpg",
      writeup: "",
      author: "",
      images: ["/assets/destinations/Kolkata/1.jpg", "/assets/destinations/Kolkata/2.jpg", "/assets/destinations/Kolkata/3.jpg", "/assets/destinations/Kolkata/4.jpg", "/assets/destinations/Kolkata/5.jpg"]
    }]
  },
  {
    slug: "kochi",
    name: "Kochi",
    cover: "/assets/portfolio/maroon-embossed-paw-trail.png",
    intro: "A coastal meeting point of culture, craft and contemporary experience.",
    events: [{
      slug: "icwf",
      title: "ICWF",
      label: "Experience · Kochi",
      cover: "/assets/portfolio/maroon-embossed-paw-trail.png",
      writeup: "",
      author: "",
      images: ["/assets/portfolio/maroon-embossed-paw-trail.png"]
    }]
  },
  {
    slug: "thailand",
    name: "Thailand",
    cover: "/assets/hua-hin.jpeg",
    intro: "Destination celebrations framed by tropical landscapes and an unmistakable sense of escape.",
    events: [{
      slug: "ritika-manav",
      title: "Ritika & Manav",
      label: "Wedding · Thailand",
      cover: "/assets/hua-hin.jpeg",
      writeup: "",
      author: "",
      images: [
        "/assets/portfolio/thailand/ritika-manav/01.jpg",
        "/assets/portfolio/thailand/ritika-manav/02.jpg",
        "/assets/portfolio/thailand/ritika-manav/03.jpg",
        "/assets/portfolio/thailand/ritika-manav/04.jpg",
        "/assets/portfolio/thailand/ritika-manav/05.jpg",
        "/assets/portfolio/thailand/ritika-manav/06.jpg",
        "/assets/portfolio/thailand/ritika-manav/07.jpg",
        "/assets/portfolio/thailand/ritika-manav/08.jpg",
        "/assets/portfolio/thailand/ritika-manav/09.jpg"
      ]
    }]
  },
  {
    slug: "istanbul",
    name: "Istanbul",
    cover: "/assets/destinations/Istanbul/1.jpg",
    intro: "Old-world opulence and contemporary spectacle at the meeting point of continents.",
    events: [{
      slug: "icwf-2019",
      title: "ICWF",
      label: "Experience · Istanbul",
      cover: "/assets/destinations/Istanbul/1.jpg",
      writeup: "",
      author: "",
      images: ["/assets/destinations/Istanbul/1.jpg", "/assets/destinations/Istanbul/2.jpg", "/assets/destinations/Istanbul/3.jpg", "/assets/destinations/Istanbul/4.jpg", "/assets/destinations/Istanbul/5.jpg"]
    }]
  },
  {
    slug: "venice",
    name: "Venice",
    cover: "/assets/destinations/Venice.webp",
    intro: "An atmospheric, after-dark experience shaped through reflection, light and dramatic scale.",
    events: [{
      slug: "icwf-2019",
      title: "ICWF",
      label: "Experience · Venice",
      cover: "/assets/destinations/Venice.webp",
      writeup: "",
      author: "",
      images: ["/assets/destinations/Venice.webp"]
    }]
  }
];
// Drive-sourced galleries are intentionally file-name driven: only Cover and
// numbered images are used. Event and destination names remain unchanged.
window.MWAP_DRIVE_PORTFOLIO_ASSETS = {
  "delhi/mithali-arjun": [
    "/assets/portfolio/delhi/mithali-arjun/cover.jpg",
    "/assets/portfolio/delhi/mithali-arjun/01.jpg",
    "/assets/portfolio/delhi/mithali-arjun/02.jpg",
    "/assets/portfolio/delhi/mithali-arjun/03.jpg",
    "/assets/portfolio/delhi/mithali-arjun/04.jpg",
    "/assets/portfolio/delhi/mithali-arjun/05.jpg",
    "/assets/portfolio/delhi/mithali-arjun/06.jpg",
    "/assets/portfolio/delhi/mithali-arjun/07.jpg",
    "/assets/portfolio/delhi/mithali-arjun/08.jpg",
    "/assets/portfolio/delhi/mithali-arjun/09.jpg",
    "/assets/portfolio/delhi/mithali-arjun/10.jpg",
    "/assets/portfolio/delhi/mithali-arjun/11.jpg",
    "/assets/portfolio/delhi/mithali-arjun/12.jpg",
    "/assets/portfolio/delhi/mithali-arjun/13.jpg",
    "/assets/portfolio/delhi/mithali-arjun/14.jpg",
    "/assets/portfolio/delhi/mithali-arjun/15.jpg",
    "/assets/portfolio/delhi/mithali-arjun/16.jpg",
    "/assets/portfolio/delhi/mithali-arjun/17.jpg",
    "/assets/portfolio/delhi/mithali-arjun/18.jpg",
    "/assets/portfolio/delhi/mithali-arjun/19.jpg"
  ],
  "delhi/bindya-shiven": [
    "/assets/portfolio/delhi/bindya-shiven/cover.jpg",
    "/assets/portfolio/delhi/bindya-shiven/01.jpg",
    "/assets/portfolio/delhi/bindya-shiven/02.jpg",
    "/assets/portfolio/delhi/bindya-shiven/03.jpg",
    "/assets/portfolio/delhi/bindya-shiven/04.jpg",
    "/assets/portfolio/delhi/bindya-shiven/05.jpg",
    "/assets/portfolio/delhi/bindya-shiven/06.jpg",
    "/assets/portfolio/delhi/bindya-shiven/07.jpg",
    "/assets/portfolio/delhi/bindya-shiven/08.jpg",
    "/assets/portfolio/delhi/bindya-shiven/09.jpg",
    "/assets/portfolio/delhi/bindya-shiven/10.jpg",
    "/assets/portfolio/delhi/bindya-shiven/11.jpg",
    "/assets/portfolio/delhi/bindya-shiven/12.jpg",
    "/assets/portfolio/delhi/bindya-shiven/13.jpg",
    "/assets/portfolio/delhi/bindya-shiven/14.jpg",
    "/assets/portfolio/delhi/bindya-shiven/15.jpg"
  ],
  "delhi/tanvi-uday": [
    "/assets/portfolio/delhi/tanvi-uday/cover.jpg",
    "/assets/portfolio/delhi/tanvi-uday/01.jpg",
    "/assets/portfolio/delhi/tanvi-uday/02.jpg",
    "/assets/portfolio/delhi/tanvi-uday/03.jpg",
    "/assets/portfolio/delhi/tanvi-uday/04.jpg",
    "/assets/portfolio/delhi/tanvi-uday/05.jpg",
    "/assets/portfolio/delhi/tanvi-uday/06.jpg",
    "/assets/portfolio/delhi/tanvi-uday/07.jpg",
    "/assets/portfolio/delhi/tanvi-uday/08.jpg",
    "/assets/portfolio/delhi/tanvi-uday/09.jpg",
    "/assets/portfolio/delhi/tanvi-uday/10.jpg",
    "/assets/portfolio/delhi/tanvi-uday/11.jpg",
    "/assets/portfolio/delhi/tanvi-uday/12.jpg",
    "/assets/portfolio/delhi/tanvi-uday/13.jpg",
    "/assets/portfolio/delhi/tanvi-uday/14.jpg",
    "/assets/portfolio/delhi/tanvi-uday/15.jpg",
    "/assets/portfolio/delhi/tanvi-uday/16.jpg"
  ],
  "jaipur/meher-aman": [
    "/assets/portfolio/jaipur/meher-aman/cover.jpg",
    "/assets/portfolio/jaipur/meher-aman/01.jpg",
    "/assets/portfolio/jaipur/meher-aman/02.jpg",
    "/assets/portfolio/jaipur/meher-aman/03.jpg",
    "/assets/portfolio/jaipur/meher-aman/04.jpg",
    "/assets/portfolio/jaipur/meher-aman/05.jpg",
    "/assets/portfolio/jaipur/meher-aman/06.jpg",
    "/assets/portfolio/jaipur/meher-aman/07.jpg",
    "/assets/portfolio/jaipur/meher-aman/08.jpg",
    "/assets/portfolio/jaipur/meher-aman/09.jpg",
    "/assets/portfolio/jaipur/meher-aman/10.jpg",
    "/assets/portfolio/jaipur/meher-aman/11.jpg",
    "/assets/portfolio/jaipur/meher-aman/12.jpg",
    "/assets/portfolio/jaipur/meher-aman/13.jpg",
    "/assets/portfolio/jaipur/meher-aman/14.jpg",
    "/assets/portfolio/jaipur/meher-aman/15.jpg",
    "/assets/portfolio/jaipur/meher-aman/16.jpg",
    "/assets/portfolio/jaipur/meher-aman/17.jpg",
    "/assets/portfolio/jaipur/meher-aman/18.jpg",
    "/assets/portfolio/jaipur/meher-aman/19.jpg",
    "/assets/portfolio/jaipur/meher-aman/20.jpg",
    "/assets/portfolio/jaipur/meher-aman/21.jpg"
  ],
  "jaipur/manat-samrath": [
    "/assets/portfolio/jaipur/manat-samrath/cover.jpg",
    "/assets/portfolio/jaipur/manat-samrath/01.jpg",
    "/assets/portfolio/jaipur/manat-samrath/02.jpg",
    "/assets/portfolio/jaipur/manat-samrath/03.jpg",
    "/assets/portfolio/jaipur/manat-samrath/04.jpg",
    "/assets/portfolio/jaipur/manat-samrath/05.jpg",
    "/assets/portfolio/jaipur/manat-samrath/06.jpg",
    "/assets/portfolio/jaipur/manat-samrath/07.jpg",
    "/assets/portfolio/jaipur/manat-samrath/08.jpg",
    "/assets/portfolio/jaipur/manat-samrath/09.jpg",
    "/assets/portfolio/jaipur/manat-samrath/10.jpg",
    "/assets/portfolio/jaipur/manat-samrath/11.jpg",
    "/assets/portfolio/jaipur/manat-samrath/12.jpg",
    "/assets/portfolio/jaipur/manat-samrath/13.jpg",
    "/assets/portfolio/jaipur/manat-samrath/14.jpg",
    "/assets/portfolio/jaipur/manat-samrath/15.jpg",
    "/assets/portfolio/jaipur/manat-samrath/16.jpg",
    "/assets/portfolio/jaipur/manat-samrath/17.jpg",
    "/assets/portfolio/jaipur/manat-samrath/18.jpg",
    "/assets/portfolio/jaipur/manat-samrath/19.jpg",
    "/assets/portfolio/jaipur/manat-samrath/20.jpg",
    "/assets/portfolio/jaipur/manat-samrath/21.jpg"
  ],
  "udaipur/sehaj-harsimar": [
    "/assets/portfolio/udaipur/sehaj-harsimar/cover.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/01.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/02.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/03.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/04.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/05.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/06.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/07.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/08.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/09.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/10.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/11.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/12.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/13.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/14.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/15.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/16.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/17.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/18.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/19.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/20.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/21.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/22.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/23.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/24.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/25.jpg",
    "/assets/portfolio/udaipur/sehaj-harsimar/26.jpg"
  ],
  "udaipur/jigyasa-samar": [
    "/assets/portfolio/udaipur/jigyasa-samar/cover.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/01.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/02.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/03.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/04.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/05.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/06.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/07.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/08.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/09.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/10.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/11.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/12.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/13.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/14.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/15.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/16.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/17.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/18.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/19.jpg",
    "/assets/portfolio/udaipur/jigyasa-samar/20.jpg"
  ],
  "goa/juhi-jatin": [
    "/assets/portfolio/goa/juhi-jatin/cover.jpg",
    "/assets/portfolio/goa/juhi-jatin/01.jpg",
    "/assets/portfolio/goa/juhi-jatin/02.jpg",
    "/assets/portfolio/goa/juhi-jatin/03.jpg",
    "/assets/portfolio/goa/juhi-jatin/04.jpg",
    "/assets/portfolio/goa/juhi-jatin/05.jpg",
    "/assets/portfolio/goa/juhi-jatin/06.jpg",
    "/assets/portfolio/goa/juhi-jatin/07.jpg",
    "/assets/portfolio/goa/juhi-jatin/08.jpg",
    "/assets/portfolio/goa/juhi-jatin/09.jpg",
    "/assets/portfolio/goa/juhi-jatin/10.jpg",
    "/assets/portfolio/goa/juhi-jatin/11.jpg",
    "/assets/portfolio/goa/juhi-jatin/12.jpg",
    "/assets/portfolio/goa/juhi-jatin/13.jpg",
    "/assets/portfolio/goa/juhi-jatin/14.jpg",
    "/assets/portfolio/goa/juhi-jatin/15.jpg",
    "/assets/portfolio/goa/juhi-jatin/16.jpg"
  ],
  "bangalore/icwf": [
    "/assets/portfolio/bangalore/icwf/01.jpg",
    "/assets/portfolio/bangalore/icwf/02.jpg",
    "/assets/portfolio/bangalore/icwf/03.png",
    "/assets/portfolio/bangalore/icwf/04.png",
    "/assets/portfolio/bangalore/icwf/05.png",
    "/assets/portfolio/bangalore/icwf-2022/1.jpg",
    "/assets/portfolio/bangalore/icwf-2022/2.jpg",
    "/assets/portfolio/bangalore/icwf-2022/3.jpg",
    "/assets/portfolio/bangalore/icwf-2022/4.jpg",
    "/assets/portfolio/bangalore/icwf-2022/5.jpg",
    "/assets/portfolio/bangalore/icwf-2022/6.jpg",
    "/assets/portfolio/bangalore/icwf-2022/7.jpg",
    "/assets/portfolio/bangalore/icwf-2022/8.jpg",
    "/assets/portfolio/bangalore/icwf-2022/9.jpg",
    "/assets/portfolio/bangalore/icwf-2022/10.jpg"
  ],
  "indore/juhi-jatin": [
    "/assets/portfolio/indore/juhi-jatin/cover.jpg",
    "/assets/portfolio/indore/juhi-jatin/01.jpg",
    "/assets/portfolio/indore/juhi-jatin/02.jpg",
    "/assets/portfolio/indore/juhi-jatin/03.jpg",
    "/assets/portfolio/indore/juhi-jatin/04.jpg",
    "/assets/portfolio/indore/juhi-jatin/05.jpg",
    "/assets/portfolio/indore/juhi-jatin/06.jpg",
    "/assets/portfolio/indore/juhi-jatin/07.jpg",
    "/assets/portfolio/indore/juhi-jatin/08.jpg",
    "/assets/portfolio/indore/juhi-jatin/09.jpg",
    "/assets/portfolio/indore/juhi-jatin/10.jpg",
    "/assets/portfolio/indore/juhi-jatin/11.jpg",
    "/assets/portfolio/indore/juhi-jatin/12.jpg",
    "/assets/portfolio/indore/juhi-jatin/13.jpg",
    "/assets/portfolio/indore/juhi-jatin/14.jpg",
    "/assets/portfolio/indore/juhi-jatin/15.jpg",
    "/assets/portfolio/indore/juhi-jatin/16.jpg",
    "/assets/portfolio/indore/juhi-jatin/17.jpg",
    "/assets/portfolio/indore/juhi-jatin/18.jpg",
    "/assets/portfolio/indore/juhi-jatin/19.jpg",
    "/assets/portfolio/indore/juhi-jatin/20.jpg"
  ],
  "thailand/ritika-manav": [
    "/assets/portfolio/thailand/ritika-manav/01.jpg",
    "/assets/portfolio/thailand/ritika-manav/02.jpg",
    "/assets/portfolio/thailand/ritika-manav/03.jpg",
    "/assets/portfolio/thailand/ritika-manav/04.jpg",
    "/assets/portfolio/thailand/ritika-manav/05.jpg",
    "/assets/portfolio/thailand/ritika-manav/06.jpg",
    "/assets/portfolio/thailand/ritika-manav/07.jpg",
    "/assets/portfolio/thailand/ritika-manav/08.jpg",
    "/assets/portfolio/thailand/ritika-manav/09.jpg"
  ],
  "istanbul/icwf": [
    "/assets/portfolio/istanbul/icwf/01.jpg",
    "/assets/portfolio/istanbul/icwf/02.jpg",
    "/assets/portfolio/istanbul/icwf/03.jpg",
    "/assets/portfolio/istanbul/icwf/04.jpg",
    "/assets/portfolio/istanbul/icwf/05.jpg"
  ]
};

window.MWAP_PORTFOLIO.forEach(destination => {
  destination.events.forEach(event => {
    const images = window.MWAP_DRIVE_PORTFOLIO_ASSETS[`${destination.slug}/${event.slug}`];
    if (!images?.length) return;
    event.images = images;
    event.cover = images.find(src => /\/cover\.[^/]+$/i.test(src)) || images[0];
  });
  const firstEventCover = destination.events.find(event => event.cover)?.cover;
  if (firstEventCover) destination.cover = firstEventCover;
});
window.MWAP_DRIVE_RATIOS = {
  "/assets/portfolio/delhi/mithali-arjun/19.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/18.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/17.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/16.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/15.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/14.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/13.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/12.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/11.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/10.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/09.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/08.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/07.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/06.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/05.jpg": 1.308,
  "/assets/portfolio/delhi/mithali-arjun/04.jpg": 0.667,
  "/assets/portfolio/delhi/mithali-arjun/03.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/02.jpg": 1.5,
  "/assets/portfolio/delhi/mithali-arjun/01.jpg": 0.697,
  "/assets/portfolio/delhi/mithali-arjun/cover.jpg": 1.501,
  "/assets/portfolio/delhi/bindya-shiven/15.jpg": 1.5,
  "/assets/portfolio/delhi/bindya-shiven/13.jpg": 1.5,
  "/assets/portfolio/delhi/bindya-shiven/14.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/12.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/11.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/10.jpg": 1.5,
  "/assets/portfolio/delhi/bindya-shiven/09.jpg": 1.499,
  "/assets/portfolio/delhi/bindya-shiven/08.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/07.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/06.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/05.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/04.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/03.jpg": 1.5,
  "/assets/portfolio/delhi/bindya-shiven/02.jpg": 1.5,
  "/assets/portfolio/delhi/bindya-shiven/01.jpg": 0.667,
  "/assets/portfolio/delhi/bindya-shiven/cover.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/16.jpg": 0.649,
  "/assets/portfolio/delhi/tanvi-uday/15.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/14.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/13.jpg": 0.669,
  "/assets/portfolio/delhi/tanvi-uday/12.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/10.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/11.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/09.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/08.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/07.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/06.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/05.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/04.jpg": 1.5,
  "/assets/portfolio/delhi/tanvi-uday/03.jpg": 1.429,
  "/assets/portfolio/delhi/tanvi-uday/02.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/01.jpg": 0.667,
  "/assets/portfolio/delhi/tanvi-uday/cover.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/21.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/20.jpg": 0.685,
  "/assets/portfolio/jaipur/meher-aman/19.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/18.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/17.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/16.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/15.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/14.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/13.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/12.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/11.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/10.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/09.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/08.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/07.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/06.jpg": 0.667,
  "/assets/portfolio/jaipur/meher-aman/05.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/04.jpg": 0.713,
  "/assets/portfolio/jaipur/meher-aman/03.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/02.jpg": 0.664,
  "/assets/portfolio/jaipur/meher-aman/01.jpg": 1.5,
  "/assets/portfolio/jaipur/meher-aman/cover.jpg": 0.675,
  "/assets/portfolio/jaipur/manat-samrath/21.jpg": 0.667,
  "/assets/portfolio/jaipur/manat-samrath/20.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/19.jpg": 0.667,
  "/assets/portfolio/jaipur/manat-samrath/18.jpg": 0.624,
  "/assets/portfolio/jaipur/manat-samrath/17.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/16.jpg": 1,
  "/assets/portfolio/jaipur/manat-samrath/15.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/14.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/13.jpg": 1,
  "/assets/portfolio/jaipur/manat-samrath/12.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/11.jpg": 1.333,
  "/assets/portfolio/jaipur/manat-samrath/10.jpg": 0.667,
  "/assets/portfolio/jaipur/manat-samrath/09.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/08.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/07.jpg": 0.667,
  "/assets/portfolio/jaipur/manat-samrath/06.jpg": 1.25,
  "/assets/portfolio/jaipur/manat-samrath/05.jpg": 1.25,
  "/assets/portfolio/jaipur/manat-samrath/04.jpg": 1,
  "/assets/portfolio/jaipur/manat-samrath/03.jpg": 1.5,
  "/assets/portfolio/jaipur/manat-samrath/02.jpg": 0.8,
  "/assets/portfolio/jaipur/manat-samrath/01.jpg": 0.667,
  "/assets/portfolio/jaipur/manat-samrath/cover.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/26.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/cover.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/25.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/24.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/23.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/22.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/21.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/20.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/19.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/18.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/17.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/16.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/15.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/14.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/13.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/12.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/10.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/11.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/09.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/08.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/07.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/06.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/05.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/04.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/03.jpg": 0.667,
  "/assets/portfolio/udaipur/sehaj-harsimar/02.jpg": 1.5,
  "/assets/portfolio/udaipur/sehaj-harsimar/01.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/20.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/19.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/18.jpg": 1.499,
  "/assets/portfolio/udaipur/jigyasa-samar/17.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/16.jpg": 1.499,
  "/assets/portfolio/udaipur/jigyasa-samar/15.jpg": 1.5,
  "/assets/portfolio/udaipur/jigyasa-samar/14.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/13.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/12.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/11.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/10.jpg": 1.5,
  "/assets/portfolio/udaipur/jigyasa-samar/09.jpg": 1.5,
  "/assets/portfolio/udaipur/jigyasa-samar/08.jpg": 1.5,
  "/assets/portfolio/udaipur/jigyasa-samar/07.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/06.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/05.jpg": 1.5,
  "/assets/portfolio/udaipur/jigyasa-samar/04.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/03.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/02.jpg": 1.499,
  "/assets/portfolio/udaipur/jigyasa-samar/01.jpg": 0.667,
  "/assets/portfolio/udaipur/jigyasa-samar/cover.jpg": 0.667,
  "/assets/portfolio/goa/juhi-jatin/10.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/11.jpg": 1.498,
  "/assets/portfolio/goa/juhi-jatin/12.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/13.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/14.jpg": 1.498,
  "/assets/portfolio/goa/juhi-jatin/15.jpg": 1.495,
  "/assets/portfolio/goa/juhi-jatin/16.jpg": 1.495,
  "/assets/portfolio/goa/juhi-jatin/09.jpg": 0.667,
  "/assets/portfolio/goa/juhi-jatin/08.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/07.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/06.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/05.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/04.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/03.jpg": 0.667,
  "/assets/portfolio/goa/juhi-jatin/01.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/02.jpg": 1.5,
  "/assets/portfolio/goa/juhi-jatin/cover.jpg": 0.667,
  "/assets/portfolio/bangalore/icwf/05.png": 1.494,
  "/assets/portfolio/bangalore/icwf-2022/1.jpg": 1.378,
  "/assets/portfolio/bangalore/icwf-2022/2.jpg": 1.02,
  "/assets/portfolio/bangalore/icwf-2022/3.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/4.jpg": 1.678,
  "/assets/portfolio/bangalore/icwf-2022/5.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/6.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/7.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/8.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/9.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf-2022/10.jpg": 1.5,
  "/assets/portfolio/bangalore/icwf/04.png": 1.495,
  "/assets/portfolio/bangalore/icwf/02.jpg": 1.459,
  "/assets/portfolio/bangalore/icwf/03.png": 1.499,
  "/assets/portfolio/bangalore/icwf/01.jpg": 1.501,
  "/assets/portfolio/indore/juhi-jatin/20.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/19.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/18.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/17.jpg": 1.499,
  "/assets/portfolio/indore/juhi-jatin/16.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/15.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/14.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/13.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/12.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/11.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/10.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/cover.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/09.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/08.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/07.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/06.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/05.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/04.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/03.jpg": 0.667,
  "/assets/portfolio/indore/juhi-jatin/02.jpg": 1.5,
  "/assets/portfolio/indore/juhi-jatin/01.jpg": 1.5,
  "/assets/portfolio/thailand/ritika-manav/06.jpg": 1.502,
  "/assets/portfolio/thailand/ritika-manav/09.jpg": 0.666,
  "/assets/portfolio/thailand/ritika-manav/07.jpg": 0.666,
  "/assets/portfolio/thailand/ritika-manav/08.jpg": 1.502,
  "/assets/portfolio/thailand/ritika-manav/02.jpg": 1.502,
  "/assets/portfolio/thailand/ritika-manav/05.jpg": 1.502,
  "/assets/portfolio/thailand/ritika-manav/03.jpg": 0.665,
  "/assets/portfolio/thailand/ritika-manav/04.jpg": 0.665,
  "/assets/portfolio/thailand/ritika-manav/01.jpg": 0.665,
  "/assets/portfolio/istanbul/icwf/05.jpg": 1.5,
  "/assets/portfolio/istanbul/icwf/01.jpg": 1,
  "/assets/portfolio/istanbul/icwf/03.jpg": 1.221,
  "/assets/portfolio/istanbul/icwf/04.jpg": 1.5,
  "/assets/portfolio/istanbul/icwf/02.jpg": 1
};
